### ISSUE TITLE
can we get a process in place for tagging public DBP repos?

### ISSUE THREAD

**Issue by rgauss** [Activiti/activiti-cloud-gateway#22]
Copied/changed from https://github.com/Alfresco/alfresco-keycloak-deployment/issues/14 by @ryandawsonuk:

Currently github.com/Activiti/activiti-cloud-gateway points here and so Activiti is releasing monthly through https://hub.docker.com/r/activiti/activiti-cloud-gateway/

Activiti can stop doing this but there should be alternative tags available to point to so that Activiti can say which version of a DBP component each Activiti release works against (much like in https://github.com/Activiti/activiti-cloud-examples/blob/7-201712-EA/docker/infrastructure-docker.yml#L9)

This presently applies to keycloak-deployment and gateway

**Comment by rgauss** [comment]
This should be included as part of [DEPLOY-272](https://issues.alfresco.com/jira/browse/DEPLOY-272) (private link) which concerns the release process of these types of artifacts.

@ryandawsonuk, in your opinion, would creating a **0.1** version work in this case?

**Comment by ghost** [comment]
This repository is now archived and no longer supported. Closing old issues.
